'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import styles from './page.module.css';
type RequestRecord={id:string;type:string;status:string;note:string|null;createdAt:string;user:string};
export default function GovernanceClient({ requests, audits, securityEvents }: { requests: RequestRecord[]; audits: Array<{id:number;action:string;entity:string;createdAt:string;user:string}>; securityEvents: Array<{id:number;event_type:string;severity:string;created_at:string}> }) {
  const router=useRouter(); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState('');
  const review=async(id:string,status:string)=>{setBusy(id);const response=await fetch(`/api/admin/governance/data-requests/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setBusy('');setNotice(response.ok?'Status permintaan diperbarui.':(await response.json()).error??'Permintaan belum dapat diperbarui.');if(response.ok)router.refresh();};
  return <section className={styles.page}><header><p>ENTERPRISE GOVERNANCE</p><h1>Audit &amp; privasi</h1><span>Catatan audit dan permintaan privasi hanya tersedia bagi Admin dengan MFA saat kebijakan MFA diaktifkan.</span></header>{notice&&<p className={styles.notice}>{notice}</p>}<div className={styles.grid}><article><h2>Permintaan data</h2>{requests.length?requests.map((item)=><div className={styles.item} key={item.id}><div><strong>{item.type} · {item.user}</strong><small>{new Date(item.createdAt).toLocaleString('id-ID')} · {item.status}</small>{item.note&&<p>{item.note}</p>}</div>{!['completed','rejected'].includes(item.status)&&<div><button disabled={busy===item.id} onClick={()=>review(item.id,'in_review')}>Tinjau</button><button disabled={busy===item.id} onClick={()=>review(item.id,'completed')}>Selesai</button><button disabled={busy===item.id} onClick={()=>review(item.id,'rejected')}>Tolak</button></div>}</div>):<p>Belum ada permintaan.</p>}</article><article><h2>Security events</h2>{securityEvents.length?securityEvents.map((item)=><div className={styles.item} key={item.id}><strong>{item.event_type}</strong><small>{item.severity} · {new Date(item.created_at).toLocaleString('id-ID')}</small></div>):<p>Belum ada security event.</p>}</article><article className={styles.wide}><h2>Audit terbaru</h2><div className={styles.tableWrap}><table><thead><tr><th>Waktu</th><th>Aktivitas</th><th>Resource</th><th>Pelaku</th></tr></thead><tbody>{audits.map((item)=><tr key={item.id}><td>{new Date(item.createdAt).toLocaleString('id-ID')}</td><td>{item.action}</td><td>{item.entity}</td><td>{item.user}</td></tr>)}{!audits.length&&<tr><td colSpan={4}>Belum ada audit record.</td></tr>}</tbody></table></div></article></div></section>;
}
