'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import styles from './page.module.css';
export default function PrivacyClient({ requests }: { requests: Array<{ id: string; request_type: string; status: string; note: string | null; resolution_note: string | null; created_at: string }> }) {
  const router = useRouter(); const [type, setType] = useState('access'); const [note, setNote] = useState(''); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSending(true); const response = await fetch('/api/privacy/requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestType: type, note }) }); setSending(false); const body = await response.json(); if (!response.ok) return setMessage(body.error ?? 'Permintaan belum dapat dikirim.'); setMessage('Permintaan telah diterima. Tim privasi akan meninjaunya.'); setNote(''); router.refresh(); };
  return <main className={styles.main}><article className={styles.wrap}><Link href="/account" className={styles.back}>← Akun Saya</Link><p className={styles.eyebrow}>PRIVASI DATA</p><h1>Kelola data Anda</h1><p className={styles.lead}>Ajukan akses, ekspor, atau penghapusan data. Penghapusan dapat dibatasi oleh kewajiban transaksi dan hukum yang berlaku.</p>{message && <p className={styles.message}>{message}</p>}<form onSubmit={submit}><label>Jenis permintaan<select value={type} onChange={(event) => setType(event.target.value)}><option value="access">Akses data</option><option value="export">Ekspor data</option><option value="erasure">Penghapusan data</option></select></label><label>Catatan (opsional)<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} /></label><button disabled={sending}>{sending ? 'Mengirim…' : 'Kirim permintaan'}</button></form><section><h2>Riwayat permintaan</h2>{requests.length ? requests.map((item) => <div className={styles.request} key={item.id}><div><strong>{item.request_type}</strong><small>{new Date(item.created_at).toLocaleDateString('id-ID')}</small></div><span>{item.status}</span>{item.resolution_note && <p>{item.resolution_note}</p>}</div>) : <p>Belum ada permintaan.</p>}</section></article></main>;
}
