// ============================================================
// WINA JAYA — Mock Data for MVP
// Data produk kain realistis untuk demo
// ============================================================

import { Product, CompanyInfo, RFQ } from '@/types';

export const companyInfo: CompanyInfo = {
  name: 'Wina Jaya',
  tagline: 'Produsen Kain Tekstil Terpercaya Sejak 1995',
  description:
    'PT. Wina Jaya Textile adalah produsen kain tekstil terkemuka di Indonesia yang telah melayani industri garmen dan fashion selama lebih dari 30 tahun. Dengan fasilitas produksi modern seluas 15.000 m² dan kapasitas produksi 500.000 meter per bulan, kami siap memenuhi kebutuhan kain Anda — dari retail hingga volume besar.',
  founded: 1995,
  address: 'Jl. Raya Industri Tekstil No. 88, Bandung, Jawa Barat 40553',
  phone: '+62 22 7234 5678',
  email: 'info@winajaya.co.id',
  whatsapp: '+6281234567890',
  certifications: ['ISO 9001:2015', 'OEKO-TEX Standard 100', 'Global Organic Textile Standard (GOTS)'],
  capacity: '500.000 meter/bulan',
  totalClients: 350,
  totalProducts: 120,
};

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Katun Combed 30s Premium',
    slug: 'katun-combed-30s-premium',
    sku: 'KC-30S-PRM',
    category: 'Katun',
    composition: '100% Cotton Combed',
    gsm: 180,
    widthCm: 160,
    pricePerMeter: 65000,
    stockMeters: 2500,
    moqRetail: 100,
    isCustomOnly: false,
    images: ['/images/products/katun-combed-1.jpg', '/images/products/katun-combed-2.jpg'],
    description:
      'Kain katun combed 30s premium dengan tekstur halus dan lembut. Sangat cocok untuk kaos, t-shirt, dan pakaian kasual premium. Telah melalui proses combing untuk menghilangkan serat pendek, menghasilkan permukaan kain yang lebih rata dan nyaman di kulit.',
    certifications: ['OEKO-TEX Standard 100'],
    variants: [
      { id: 'v-001-1', productId: 'prod-001', colorName: 'Putih', colorHex: '#FFFFFF', stock: 800 },
      { id: 'v-001-2', productId: 'prod-001', colorName: 'Hitam', colorHex: '#1a1a1a', stock: 600 },
      { id: 'v-001-3', productId: 'prod-001', colorName: 'Navy', colorHex: '#0a1628', stock: 450 },
      { id: 'v-001-4', productId: 'prod-001', colorName: 'Abu-abu Misty', colorHex: '#B0B0B0', stock: 350 },
      { id: 'v-001-5', productId: 'prod-001', colorName: 'Maroon', colorHex: '#800020', stock: 300 },
    ],
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Polyester Mikro Interlock',
    slug: 'polyester-mikro-interlock',
    sku: 'PL-MKR-INT',
    category: 'Polyester',
    composition: '100% Polyester Micro',
    gsm: 220,
    widthCm: 150,
    pricePerMeter: 48000,
    stockMeters: 3200,
    moqRetail: 150,
    isCustomOnly: false,
    images: ['/images/products/polyester-micro-1.jpg', '/images/products/polyester-micro-2.jpg'],
    description:
      'Kain polyester mikro interlock berkualitas tinggi dengan daya serap keringat yang baik. Ideal untuk jersey olahraga, seragam, dan pakaian aktif. Tahan luntur warna dan mudah perawatannya.',
    certifications: [],
    variants: [
      { id: 'v-002-1', productId: 'prod-002', colorName: 'Putih', colorHex: '#FFFFFF', stock: 1000 },
      { id: 'v-002-2', productId: 'prod-002', colorName: 'Merah', colorHex: '#DC2626', stock: 700 },
      { id: 'v-002-3', productId: 'prod-002', colorName: 'Biru Royal', colorHex: '#1D4ED8', stock: 500 },
      { id: 'v-002-4', productId: 'prod-002', colorName: 'Kuning', colorHex: '#EAB308', stock: 400 },
    ],
    createdAt: '2024-02-10T08:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Rayon Viscose Premium',
    slug: 'rayon-viscose-premium',
    sku: 'RY-VSC-PRM',
    category: 'Rayon',
    composition: '100% Rayon Viscose',
    gsm: 130,
    widthCm: 150,
    pricePerMeter: 55000,
    stockMeters: 1800,
    moqRetail: 50,
    isCustomOnly: false,
    images: ['/images/products/rayon-viscose-1.jpg', '/images/products/rayon-viscose-2.jpg'],
    description:
      'Kain rayon viscose premium yang jatuh indah dengan draping excellent. Sempurna untuk gamis, blouse, dress, dan busana muslim. Adem dipakai dan menyerap keringat dengan baik.',
    certifications: ['OEKO-TEX Standard 100', 'GOTS'],
    variants: [
      { id: 'v-003-1', productId: 'prod-003', colorName: 'Dusty Pink', colorHex: '#D4A0A0', stock: 500 },
      { id: 'v-003-2', productId: 'prod-003', colorName: 'Sage Green', colorHex: '#8FA387', stock: 400 },
      { id: 'v-003-3', productId: 'prod-003', colorName: 'Mocca', colorHex: '#8B7355', stock: 350 },
      { id: 'v-003-4', productId: 'prod-003', colorName: 'Navy', colorHex: '#0a1628', stock: 300 },
    ],
    createdAt: '2024-03-05T08:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Denim Selvedge 12oz',
    slug: 'denim-selvedge-12oz',
    sku: 'DN-SLV-12',
    category: 'Denim',
    composition: '100% Cotton Denim',
    gsm: 400,
    widthCm: 80,
    pricePerMeter: 120000,
    stockMeters: 800,
    moqRetail: 30,
    isCustomOnly: false,
    images: ['/images/products/denim-selvedge-1.jpg', '/images/products/denim-selvedge-2.jpg'],
    description:
      'Denim selvedge premium 12oz dengan karakter khas selvedge line merah. Ditenun dengan shuttle loom tradisional untuk menghasilkan kain yang padat dan tahan lama. Cocok untuk jeans, jaket, dan produk denim premium.',
    certifications: ['OEKO-TEX Standard 100'],
    variants: [
      { id: 'v-004-1', productId: 'prod-004', colorName: 'Indigo', colorHex: '#2E4057', stock: 400 },
      { id: 'v-004-2', productId: 'prod-004', colorName: 'Raw Indigo', colorHex: '#1B2838', stock: 250 },
      { id: 'v-004-3', productId: 'prod-004', colorName: 'Black', colorHex: '#1a1a1a', stock: 150 },
    ],
    createdAt: '2024-04-20T08:00:00Z',
  },
  {
    id: 'prod-005',
    name: 'Linen Blend French Terry',
    slug: 'linen-blend-french-terry',
    sku: 'LN-FRT-BL',
    category: 'Linen',
    composition: '55% Linen, 45% Cotton',
    gsm: 280,
    widthCm: 160,
    pricePerMeter: 95000,
    stockMeters: 600,
    moqRetail: 20,
    isCustomOnly: false,
    images: ['/images/products/linen-french-1.jpg', '/images/products/linen-french-2.jpg'],
    description:
      'Kain linen blend french terry yang menggabungkan kesan natural linen dengan kelembutan cotton. Loop terry di bagian dalam memberikan kenyamanan ekstra. Ideal untuk hoodie, sweater, dan loungewear premium.',
    certifications: ['GOTS'],
    variants: [
      { id: 'v-005-1', productId: 'prod-005', colorName: 'Natural', colorHex: '#D4C5A9', stock: 200 },
      { id: 'v-005-2', productId: 'prod-005', colorName: 'Oat', colorHex: '#C8B896', stock: 200 },
      { id: 'v-005-3', productId: 'prod-005', colorName: 'Charcoal', colorHex: '#36393D', stock: 150 },
    ],
    createdAt: '2024-05-12T08:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Jersey CVC 60/40',
    slug: 'jersey-cvc-60-40',
    sku: 'JR-CVC-60',
    category: 'Katun',
    composition: '60% Cotton, 40% Polyester',
    gsm: 190,
    widthCm: 160,
    pricePerMeter: 52000,
    stockMeters: 4500,
    moqRetail: 80,
    isCustomOnly: false,
    images: ['/images/products/jersey-cvc-1.jpg', '/images/products/jersey-cvc-2.jpg'],
    description:
      'Kain jersey CVC 60/40 yang menggabungkan kenyamanan katun dengan daya tahan polyester. Anti-pilling, tidak mudah melar, dan warna tahan lama. Pilihan populer untuk produksi kaos massal dan merchandise.',
    certifications: [],
    variants: [
      { id: 'v-006-1', productId: 'prod-006', colorName: 'Putih', colorHex: '#FFFFFF', stock: 1500 },
      { id: 'v-006-2', productId: 'prod-006', colorName: 'Hitam', colorHex: '#1a1a1a', stock: 1200 },
      { id: 'v-006-3', productId: 'prod-006', colorName: 'Navy', colorHex: '#0a1628', stock: 800 },
      { id: 'v-006-4', productId: 'prod-006', colorName: 'Abu Tua', colorHex: '#4B4B4B', stock: 500 },
      { id: 'v-006-5', productId: 'prod-006', colorName: 'Olive', colorHex: '#556B2F', stock: 300 },
    ],
    createdAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 'prod-007',
    name: 'Twill Stretch Cotton',
    slug: 'twill-stretch-cotton',
    sku: 'TW-STR-CT',
    category: 'Katun',
    composition: '97% Cotton, 3% Spandex',
    gsm: 260,
    widthCm: 150,
    pricePerMeter: 78000,
    stockMeters: 1200,
    moqRetail: 40,
    isCustomOnly: false,
    images: ['/images/products/twill-stretch-1.jpg', '/images/products/twill-stretch-2.jpg'],
    description:
      'Kain twill stretch cotton premium dengan elastisitas yang nyaman. Cocok untuk celana chino, celana kerja, dan pakaian formal kasual. Finishing soft hand feel untuk kenyamanan sepanjang hari.',
    certifications: ['OEKO-TEX Standard 100'],
    variants: [
      { id: 'v-007-1', productId: 'prod-007', colorName: 'Khaki', colorHex: '#C3B091', stock: 400 },
      { id: 'v-007-2', productId: 'prod-007', colorName: 'Navy', colorHex: '#0a1628', stock: 350 },
      { id: 'v-007-3', productId: 'prod-007', colorName: 'Hitam', colorHex: '#1a1a1a', stock: 300 },
      { id: 'v-007-4', productId: 'prod-007', colorName: 'Cokelat', colorHex: '#6F4E37', stock: 200 },
    ],
    createdAt: '2024-07-18T08:00:00Z',
  },
  {
    id: 'prod-008',
    name: 'Spandex Lycra Performance',
    slug: 'spandex-lycra-performance',
    sku: 'SP-LYC-PF',
    category: 'Spandex',
    composition: '80% Nylon, 20% Spandex',
    gsm: 200,
    widthCm: 150,
    pricePerMeter: 85000,
    stockMeters: 900,
    moqRetail: 50,
    isCustomOnly: false,
    images: ['/images/products/spandex-lycra-1.jpg', '/images/products/spandex-lycra-2.jpg'],
    description:
      'Kain spandex lycra performance dengan 4-way stretch untuk kebebasan gerak maksimal. Quick-dry dan anti-bakteri. Ideal untuk activewear, legging, sports bra, dan pakaian renang.',
    certifications: ['OEKO-TEX Standard 100'],
    variants: [
      { id: 'v-008-1', productId: 'prod-008', colorName: 'Hitam', colorHex: '#1a1a1a', stock: 400 },
      { id: 'v-008-2', productId: 'prod-008', colorName: 'Putih', colorHex: '#FFFFFF', stock: 200 },
      { id: 'v-008-3', productId: 'prod-008', colorName: 'Navy', colorHex: '#0a1628', stock: 150 },
    ],
    createdAt: '2024-08-05T08:00:00Z',
  },
  {
    id: 'prod-009',
    name: 'Custom Print Sublimation Base',
    slug: 'custom-print-sublimation-base',
    sku: 'CP-SUB-BS',
    category: 'Polyester',
    composition: '100% Polyester',
    gsm: 160,
    widthCm: 160,
    pricePerMeter: 0,
    stockMeters: 0,
    moqRetail: 500,
    isCustomOnly: true,
    images: ['/images/products/sublimation-base-1.jpg', '/images/products/sublimation-base-2.jpg'],
    description:
      'Kain base khusus untuk sublimation printing. Permukaan putih optimal untuk transfer warna. Tersedia custom motif/desain — cocok untuk produksi jersey, merchandise, dan kain bermotif custom. MOQ 500 meter per desain.',
    certifications: [],
    variants: [],
    createdAt: '2024-09-01T08:00:00Z',
  },
];

export const featuredProducts = products.slice(0, 6);

export const categories = [
  { name: 'Katun', count: 3, icon: '🧶' },
  { name: 'Polyester', count: 2, icon: '✨' },
  { name: 'Rayon', count: 1, icon: '🌿' },
  { name: 'Denim', count: 1, icon: '👖' },
  { name: 'Linen', count: 1, icon: '🌾' },
  { name: 'Spandex', count: 1, icon: '💪' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Rina Andriati',
    company: 'PT. Garmen Nusantara',
    role: 'Head of Procurement',
    content:
      'Kualitas kain dari Wina Jaya selalu konsisten. Sudah 5 tahun kami bekerja sama dan tidak pernah mengecewakan. Respon tim sales juga sangat cepat untuk RFQ kami.',
    avatar: '/images/testimonials/avatar-1.jpg',
  },
  {
    id: 2,
    name: 'Budi Santoso',
    company: 'Brand Lokal "Kayana"',
    role: 'Founder & Creative Director',
    content:
      'Sebagai brand fashion lokal, kami butuh partner yang bisa handling custom fabric. Wina Jaya punya kemampuan itu dengan harga yang masih kompetitif.',
    avatar: '/images/testimonials/avatar-2.jpg',
  },
  {
    id: 3,
    name: 'Sarah Wijaya',
    company: 'Konveksi Mandiri Jaya',
    role: 'Owner',
    content:
      'Dulu beli kain harus datang langsung ke pabrik. Sekarang lewat website bisa langsung lihat katalog dan ajukan penawaran. Sangat memudahkan!',
    avatar: '/images/testimonials/avatar-3.jpg',
  },
];

export const stats = [
  { value: '30+', label: 'Tahun Pengalaman', icon: '🏭' },
  { value: '350+', label: 'Klien Aktif', icon: '🤝' },
  { value: '500K', label: 'Meter/Bulan', icon: '📏' },
  { value: '120+', label: 'Varian Produk', icon: '🎨' },
];

export const sampleRFQs: RFQ[] = [
  {
    id: 'rfq-001',
    userId: 'user-001',
    productId: 'prod-001',
    productName: 'Katun Combed 30s Premium',
    specDetails: {
      warna: 'Custom Pantone 2728C',
      motif: 'Polos',
      gramasiTarget: 180,
      catatan: 'Butuh sample dulu sebelum order besar',
    },
    qtyRequested: 5000,
    deadline: '2024-12-01T00:00:00Z',
    status: 'SUBMITTED',
    attachments: [],
    createdAt: '2024-10-15T10:30:00Z',
  },
  {
    id: 'rfq-002',
    userId: 'user-002',
    productId: 'prod-009',
    productName: 'Custom Print Sublimation Base',
    specDetails: {
      warna: 'Full print custom',
      motif: 'Desain jersey tim futsal (file terlampir)',
      gramasiTarget: 160,
      catatan: 'Butuh 200 potong jersey ukuran M-XXL',
    },
    qtyRequested: 1000,
    deadline: '2024-11-15T00:00:00Z',
    status: 'REVIEWED',
    attachments: ['design-jersey.pdf'],
    createdAt: '2024-10-12T14:00:00Z',
  },
  {
    id: 'rfq-003',
    userId: 'user-003',
    productId: 'prod-003',
    productName: 'Rayon Viscose Premium',
    specDetails: {
      warna: 'Lavender',
      motif: 'Polos',
      gramasiTarget: 130,
      catatan: 'Untuk koleksi gamis lebaran 2025',
    },
    qtyRequested: 3000,
    deadline: '2025-01-15T00:00:00Z',
    status: 'QUOTED',
    attachments: [],
    createdAt: '2024-10-10T09:00:00Z',
  },
];
